version: '3'

services:
  app:
    build:
      context: .
      args:
        APP_NAME: porkbun-ddns-rs
    environment:
      - DDNS_API_KEY=test
      - DDNS_SECRET_KEY=test
      - DDNS_HOST=test.dev
      - DDNS_MINUTES_INTERVAL=120
    container_name: porkbun-ddns-rs
    restart: unless-stopped
    volumes:
      - "./log4rs.yaml:/etc/porkbun-ddns-rs/log4rs.yaml"
      - "./requests.log:/requests.log"
      - "/etc/localtime:/etc/localtime"